### ISSUE TITLE
A question about infer.py

### ISSUE THREAD

**Issue by kangkai98** [tansor/VecRoad#8]
Thank you for your excellent work! But I encounter a problem when I run infer.py. The problem is when I set INFER_STEP: "start", START_FROM_ROAD_PEAK: True, the file can successfully run. If I change the INFER_STEP to"after_seg", it will report an error when doing post_process_graph. Can you give me some advice? Thanks again.

infer anchor start
batch_size:1
    Except save graph yunnan_city
Traceback (most recent call last):
  File "infer.py", line 586, in <module>
    main()
  File "infer.py", line 222, in main
    post_process_graph(graph_dict)
  File "infer.py", line 425, in post_process_graph
    road_segments, _ = graph_helper.get_graph_road_segments(g)
  File "/f2020/kangkai/VecRoad/lib/graph.py", line 635, in get_graph_road_segments
    for edge in graph.edges.values():
AttributeError: 'NoneType' object has no attribute 'edges'

**Comment by tansor** [comment]
Hi, kangkau.
The log says "Except save graph yunnan_city", that means there is a bug here https://github.com/tansor/VecRoad/blob/17e78980b6eb7170702dc79663c595f26bcdb664/infer.py#L192
Please check the `except_yunnan_city.graph` file and function `infer_anchor` for more details.

**Comment by kangkai98** [comment]
Thank you for your advice!! I've solved the problem mentioned above. There's another question I want to ask, there are still some disconnected roads in the final results.  How can I adjust the parameters in default.yml to increase the road connectivity?  Thank you very much!

**Comment by ziyu1018** [comment]
HI，I had the same problem，can you tell me how to solve this problem？

**Comment by WentangChen** [comment]
> Thank you for your advice!! I've solved the problem mentioned above. There's another question I want to ask, there are still some disconnected roads in the final results. How can I adjust the parameters in default.yml to increase the road connectivity? Thank you very much!

hello , I have the same problem , can you tell me how to solve it？

**Comment by yutinyang** [comment]
Hi, I have the same problem. Can you provide the solution to solve if ?

File "xxx/VecRoad-master/lib/graph.py", line 635, in get_graph_road_segments
    for edge in graph.edges.values():
AttributeError: 'NoneType' object has no attribute 'edges'
